### ISSUE TITLE
Hobbiteffekte [Wichtig]

### ISSUE THREAD

**Issue by chincoe** [ToppseDev/ArdaCraftBugs#12]
! Hobbits haben Hunger 3 !
die grundeffekte Hunger und Nachtsicht verschwinden, wenn die anderen effekte aktiviert werden.

**Comment by tobiasnagel** [comment]
1. Bitte schreib für jeden Bug eine eigene Meldung.
2. Die eingetragenen Hobbit Effekte sind Hunger 1 dauerhaft. Überprüfe bitte, ob die Wirkung vllt. durch Brewery verursacht wird (also du dich betrunken hast).
3. schreib das bitte nochmal in nen neuen issue
