### ISSUE TITLE
Keine Witherskelette im nether mehr

### ISSUE THREAD

**Issue by chincoe** [ToppseDev/ArdaCraftBugs#13]
seit dem neuen update spawnen keine witherskelette mehr in den netherfestungen

**Comment by tobiasnagel** [comment]
ich überprüf das mal

**Comment by tobiasnagel** [comment]
![2015-12-31_13 06 20](https://cloud.githubusercontent.com/assets/9637659/12064268/5aebde5c-afbf-11e5-9eb3-c3adb05de66e.png)
Ich hab die Schwierigkeit jetzt auf Normal gesetzt in der Hölle. Insofern geht es jetzt ^^
