### ISSUE TITLE
Keine xp in der Miningwelt

### ISSUE THREAD

**Issue by chincoe** [ToppseDev/ArdaCraftBugs#17]
Tiere und Monster droppen in der miningwelt keine xp mehr

**Comment by tobiasnagel** [comment]
ist getestet, bei mir und carsten droppen tiere ind er miningwelt exp. Bitte mehr details: mit welchem item, welches mob, etc.

**Comment by tobiasnagel** [comment]
liegt wohl nicht an der miningwelt, sondern an den spezialitems, siehe #21
